name: tudat-bundle
channels:
  - conda-forge
  - tudat-team
dependencies:
  - eigen
  - boost-cpp=1.78.0
  - tudat-resources
  - sofa-cmake
  - nrlmsise-00
  - cspice-cmake
  - python=3.11
  - pybind11
  - pybind11-abi
  # Python dependencies
  - numpy<2.0.0
  - pytest
  - mypy
  - pandas     # for tudatpy.io
  - matplotlib # for tudatpy.plotting
  - tqdm       # for tudatpy.trajectory_design.porkchop
  - astropy    # for tudatpy.data.mpc
  - astroquery # for tudatpy.data.mpc
  - astropy-healpix  # for tudatpy.data._biases
  # Documentation
  - jinja2
  - pyyaml
  - pydantic == 1.10.9
  - numpydoc
  - doxygen # for cpp api
  - pip
  - pip:
     - nbsphinx
     - sphinxcontrib-napoleon
     - sphinx_rtd_theme
     - sphinxcontrib-fulltoc
     - sphinxcontrib-bibtex
     - furo
     - sphinx_copybutton 